### ISSUE TITLE
Support displaying copyable code blocks with different prefixes

### ISSUE THREAD

**Issue by ireneontheway** [pingcap/website-docs#110]
在新文档站的实现下，有没有更加高效的方式来实现 https://internal.pingcap.net/jira/browse/ICM-95 所提到的所有需求？原来每加一个 code block 都要在前面加一行 snippet 有点傻。@YiniXu9506

**Comment by YiniXu9506** [comment]
Could you please point out which part make you feel a little bit stupid? The `{{ copyable }}` or the language remark inside code block?

Since not all code blocks need to be copyable, I cannot guess which code you want it to be copyable, so you have to remark the code using snippet code.

There is no need to add `copyable` snippet code if you don't want the code to be copyable. I think this is applied to most code block.

**Comment by YiniXu9506** [comment]
@ireneontheway Reopen it if you have any problem.
